import { scrollsuave, scrolltoinit } from "./script/animacoes.js";
import jsForm from "./script/formulario.js";
import lerMais from "./script/textos.js";
import menuHamburguer from "./script/menu-hamb.js";
import mostraMapa from "./script/mostra-mapa.js";
scrollsuave();
scrolltoinit();
jsForm();
lerMais();
menuHamburguer();
mostraMapa();
